# Compose para nuvem digital ocean
#version: "3"
#services:
#  api-node-03:
#    image: registry.digitalocean.com/dcr-samuel/puc-node-api-03:${TAG}
#    container_name: puc-node-api-03
#    build: 
#      context: .
#      dockerfile: ./Dockerfile
#      args:
#        - TAG=${TAG}
#    ports:
#      - "3002:3002"


# Compose para LOCALHOST
version: "3"
services:
  api-node-03:
    image: puc-node-api-3
    container_name: puc-node-api-3
    build: .
    command: "npm run start"
    expose:
      - "3002"
    ports:
      - "3002:3002"